spring:
  application:
    name: flight
  data:
    mongodb:
      uri: mongodb+srv://hbib:Azerty%409911@cluster0.br7eade.mongodb.net/PFE?retryWrites=true&w=majority
  profiles:
    active: amadeus
  jackson:
    deserialization:
      fail-on-ignored-properties: false
server:
  port: 8050

amadeus:
  api:
    key: 8sILHrr9qpoORGbmgczUDTyfVARAAUmI
    secret: GqI0o1v8abouwgAs

logging:
  level:
    org:
      springframework:
        web: DEBUG
        http: DEBUG
        validation: TRACE
    com:
      fasterxml:
        jackson: TRACE