spring:
  application:
    name: flight
  data:
    mongodb:
      uri: mongodb://localhost:27017/PFE
  profiles:
    active: amadeus
server:
  port: 8050

amadeus:
  api:
    key: 8sILHrr9qpoORGbmgczUDTyfVARAAUmI
    secret: GqI0o1v8abouwgAs

logging:
  level:
    org:
      springframework:
        web: DEBUG
        http: DEBUG

