spring:
  application:
    name: flight
  data:
    mongodb:
      uri: mongodb://localhost:27017/PFE
server:
  port: 8050


logging:
  level:
    org:
      springframework:
        web: DEBUG
        http: DEBUG

